// Authentication Action Types
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT'; 
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'; 
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'; 
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'; 
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL'; 
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'; 
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'; 
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS'; 
export const UPDATE_EMAIL_FAIL = 'UPDATE_EMAIL_FAIL'; 
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'; 
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'; 
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'; 
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'; 
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'; 
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'; 

